herbarium/urls.py
from django.urls import path, re_path
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.views.static import serve
from django.views.generic import ListView, RedirectView
from rest_framework import routers
from api import views
from search import models

router = routers.DefaultRouter()
router.register(r"", views.PlantsViewSet)

urlpatterns = [
    path("api/data/<str:barcode>/", views.get_data),
    path("api/list/", views.get_list),
    path("api/src/<str:barcode>/", views.get_src),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    re_path(
        "collections",
        ListView.as_view(
            model=models.Plant, paginate_by=12, template_name="collections.html"
        ),
    ),
    re_path("^index", include("index.urls")),
    re_path(r"^search/", include("search.urls")),
    path("admin/", admin.site.urls),
    re_path("^$", include("index.urls")),
    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/images/favicon.ico', permanent=True))
]

# if settings.DEBUG:
urlpatterns += [
    url(r"^scans/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT, }),
    # url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]

index/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'', views.home),
]

search/urls.py
from django.urls import path, re_path
from django.conf.urls import url, include
from django.conf import settings
from django.views.static import serve

from . import views

urlpatterns = [
    re_path(r"search_result", views.search.as_view(), name="search_result"),
    # url(r'services/(?P<plant_id>\D+)', views.services),
    path(r"services/<str:barcode>", views.services),
    re_path(r"^$", views.home.as_view()),
]
if settings.DEBUG:
    urlpatterns += [
        url(r"^scans/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT, }),
    ]

search/models.py
from django.db import models

countries = (
    ("Slovensko", "Slovakia"),
    ("Cesko", "Czechia"),
    ("Rakusko", "Austria"),
    ("Polsko", "Poland"),
    ("Nemecko", "Germany"),
)


class Plant(models.Model):
    barcode = models.CharField(max_length=15, primary_key=True)
    taxon = models.CharField(max_length=30)
    locality = models.CharField(max_length=40)
    country = models.CharField(max_length=30, choices=countries, default=countries[0])
    year = models.IntegerField()
    legend_author = models.CharField(max_length=30, blank=True)
    collector = models.CharField(max_length=30, blank=True)
    scan = models.ImageField()

    def __str__(self):
        return self.taxon + ", barcode: " + self.barcode

search/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView
from django.db.models import Q

from .models import Plant


class search(ListView):
    model = Plant
    template_name = "search_result.html"
    paginate_by = 12

    def get_queryset(self):

        taxon_get = self.request.GET.get("taxon")
        country_get = self.request.GET.get("country")
        barcode_get = self.request.GET.get("barcode")
        collector_get = self.request.GET.get("collector")
        locality_get = self.request.GET.get("locality")
        year_get = self.request.GET.get("year")

        return Plant.objects.filter(
            Q(country__icontains=country_get)
            & Q(taxon__icontains=taxon_get)
            & Q(barcode__icontains=barcode_get)
            & (Q(collector__icontains=collector_get) | Q(legend_author__icontains=collector_get))
            & Q(locality__icontains=locality_get)
            & Q(year__icontains=year_get)
        )


class home(TemplateView):

    model = Plant
    template_name = "search.html"


def services(request, barcode):
    plant = Plant.objects.get(barcode=barcode)
    return render(request, "services.html", {"plant": plant})

search/templates/collections.html
{% extends "index.html" %}
{% load static %}

{% block title %}Collection {% endblock title %}

{% block content %}

{% if object_list %}

{% load thumbnail %}

<div class="container">

  <h1 class="font-weight-light text-center text-lg-left mt-4 mb-0">Collection</h1>

  <hr class="mt-2 mb-5">

  <div class="row text-center text-lg-left flex_center ">
      {% for plant in object_list %}

    <div class="col-lg-3 col-md-4 col-6 ">
        {% thumbnail plant.scan "200" as im %}
      <a target="_blank"  href="{{ plant.scan.url }}" class="d-block mb-4 h-100">
            <img title="Click for open full image" class="img-fluid img-thumbnail image_zoom" src="{{im.url }}" alt="">
          </a>
        <a  class="name_taxon" href="search/services/{{plant.barcode}}"><h2>{{plant.taxon}}</h2></a>

        {% endthumbnail %}
    </div>
      {% endfor %}
  </div>
</div>

<div >
  <ul class="pagination pagination-lg justify-content-center ">

    {% if page_obj.has_previous %}
      <li class="page-item">
        <a class=" page-link " href="?page={{ page_obj.previous_page_number }} ">Previous</a>
      </li>
    {%endif %}
    {%for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
            <li class="page-item active">
              <a class="page-link" >{{i}}</a>
            </li>
        {% else %}
            <li class="page-item">
        <a  class="page-link " href="?page={{ i }} ">{{i}}</a>
            </li>
        {%endif %}
    {% endfor %}
    {%if page_obj.has_next %}
    <li class="page-item">
        <a class=" page-link" href="?page={{ page_obj.next_page_number }} ">Next</a>
    </li>
    {% endif %}

  </ul>
</div>


{% else %}
<h1>Oops, somethings is wrong</h1>
{% endif %}

{% endblock content %}

search/templates/search.html
{% extends 'index.html' %}
{% load static %}

{% block static %}
	<script type="text/javascript" src="{%static "js/is_empty_search.js"%}"></script>
{% endblock static %}

{% block title %}Search{%endblock title %}

{%block content %}
<div class="containerer">

    <form class="" action="{% url 'search_result' %}" method="get" id="search" onsubmit="return validate_form();" >
<div class ="row">
    <div class="col-md-6">

			<div class="form-group">
				<p>Taxon:</p>
				<input name="taxon" type="text" class="form-control" placeholder="">
			</div>

			<div class="form-group">
				<p>Collector:</p>
				<input name="collector" type="text" class="form-control" placeholder="">
			</div>

			<div class="form-group">
				<p>Locality:</p>
				<input name="locality" type="text" class="form-control" placeholder="">
			</div>
	</div>

    <div class="col-md-6">
    		<div class="form-group">
				<p>Collection number</p>
				<input name="barcode" type="text" class="form-control" placeholder="">
			</div>

			<div class="form-group">
				<p>Year</p>
				<input name="year" type="text" class="form-control" placeholder="">
			</div>

			<div class="form-group">
				<p>Country:</p>
				<p><select class="form-control" name = "country">
				<option value="">--Choose country--</option>
				<option value="Slovensko">Slovakia</option>
				<option value="Cesko">Czechia</option>
				<option value="Rakusko">Austria</option>
				<option value="Polsko">Poland</option>
				<option value="Nemecko">Germany</option>
				</select></p>
			</div>

    </div>

</div>
				 <div class ="row justify-content-center">
					 <input class=" btn btn-primary btn-lg  " type="submit" name="" value="Search"  />
				 <div>
    </form>

</div>

{% endblock content%}

search/templates/search_result.html
{% extends "index.html" %}
{% load static %}
{%block title %}Search result{%endblock title %}

{% block content %}
{% if object_list %}
{% load thumbnail %}


<div class="container">

  <h1 class="font-weight-light text-center text-lg-left mt-4 mb-0">Result</h1>

  <hr class="mt-2 mb-5">

  <div class="row text-center text-lg-left flex_center">
      {% for plant in object_list %}

    <div class="col-lg-3 col-md-4 col-6 ">
        {% thumbnail plant.scan "200" as im %}
      <a target="_blank" href="{{ plant.scan.url }}" class="d-block mb-4 h-100">
            <img  title="Click for open full image" class="img-fluid img-thumbnail image_zoom" src="{{im.url }}" alt="">
          </a>

        <a  href="services/{{plant.barcode}}"><h2>{{plant.taxon}}</h2>


        {% endthumbnail %}
    </div>
      {% endfor %}
  </div>

</div>
 {% if page_obj.has_next or page_obj.has_previous %}

<div class="">
  <ul class="pagination pagination-lg justify-content-center ">

    {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}{% for key, value in request.GET.items%}{%ifnotequal key 'page'%}&{{key}}={{value}}{%endifnotequal%}{%endfor%}" >Previous</a>
      </li>
    {%endif %}
    {%for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
            <li class="page-item active">
              <a class="page-link" href="#">{{i}}</a>
            </li>
        {% else %}
            <li class="page-item">
        <a  class="page-link " href="?page={{ i }}{% for key, value in request.GET.items%}{%ifnotequal key 'page'%}&{{key}}={{value}}{%endifnotequal%}{%endfor%} ">{{i}}</a>
            </li>
        {%endif %}
    {% endfor %}
    {%if page_obj.has_next %}
    <li class="page-item">
        <a class=" page-link" href="?page={{ page_obj.next_page_number }}{% for key, value in request.GET.items%}{%ifnotequal key 'page'%}&{{key}}={{value}}{%endifnotequal%}{%endfor%}   ">Next</a>
    </li>
    {% endif %}

  </ul>
</div>
{%endif %}

{% else %}
<div class="alert alert-dismissible alert-warning">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
<!--  <h4 class="alert-heading">Warning!</h4>-->
  <p class="mb-0">Unfortunately nothing was found for the specified search parameters.<br> <a href="/search" class="alert-link">Please, change search parementres and try again</a></br></p>
</div>
{% endif %}

{% endblock content %}

search/templates/services.html
{% extends "index.html" %}
{% load static %}

{%block static  %}
<script>var crcr = '{{plant.scan.url}}' </script>
<script type="text/javascript" src="{%static "js/color_picker.js"%}"></script>
<script type="text/javascript" src="{%static "js/meassuring.js"%}"></script>

{% endblock static %}

{%block content %}
<div class="container">
    <ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link active" data-toggle="tab" id="clearer-1" href="#metadata">Metadata</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" data-toggle="tab" href="#distance">Distansce measurement</a>
  </li>
  <li class="nav-item">
    <a class="nav-link " data-toggle="tab" id="clearer-2" href="#color_picker">Color measurement</a>
  </li>
  <li class="nav-item dropdown">

  </li>
</ul>
    <div class = "row">

    <div class="col-lg-5">


<div id="myTabContent" class="tab-content">
  <div class="tab-pane fade active show" id="metadata">
	  <div class="card text-white bg-primary mb-3" style="max-width: 20rem;">
  <div class="card-header">Metadata</div>
  <div class="card-body">
    <h4 class="card-title">Taxon:{{plant.taxon}}</h4>
    <p class="card-text">Country: {{plant.get_country_display}}</p>
	  {% if plant.locality %}
    <p class="card-text">Locality: {{plant.locality}}</p>
	  {%endif%}
	  <p class="card-text">Collector: {{plant.collector}}</p>
	{% if plant.legend.author %}
		<p class="card-text">Legend author: {{plant.legend_author}}</p>
	{%endif%}
    <p class="card-text">Year: {{plant.year}}</p>

  </div>
	  </div>
      <a target="_blank" href="{{plant.scan.url}}">
          <button type="button" class="btn btn-primary">Open full image in new tab</button>
      </a>
  </div>
  <div class="tab-pane fade " id="color_picker">
        <div>Color</div>
        <div id="preview"></div>
        <div>Parameters</div>
      <div class ="params" style="max-width:30%">
        <div>R: <input  type="text" id="rVal" /></div>
        <div>G: <input type="text" id="gVal" /></div>
        <div>B: <input type="text" id="bVal" /></div>
        <div>RGB: <input type="text" id="rgbVal" /></div>
        <div>RGBA: <input type="text" id="rgbaVal" /></div>
        <div>HEX: <input type="text" id="hexVal" /></div>
      </div>
  </div>

  <div class="tab-pane fade" id="distance">
       <input style="visibility:hidden;" id=ref value=1>

            <div id=fileinfo></div>

            <div id=info>x=- y=- -</div>
            <input id=save type=button class="btn btn-primary" disabled value="Save as ...">
            <h3>Measurements</h3>
            <div id=output>None yet.</div>

  </div>

</div>

</div>

    <div class="col-lg-7">

        <canvas id="panel" > </canvas>
    </div>

   </div>
</div>
{% endblock content %}